### ISSUE TITLE
Problem with README.md name instead of README

### ISSUE THREAD

**Issue by BavarianTomcat** [jeads/datasource#19]
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    long_description=read('README'),
  File "setup.py", line 10, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
IOError: [Errno 2] No such file or directory: 'README'

mv README.md to README worked to finish install :)

**Comment by edmorley** [comment]
This was fixed by https://github.com/jeads/datasource/commit/a0196a789df4648a8affe9ea23eac5d4d18087d4
