### ISSUE TITLE
Turn the Travis switch to "on" for this repo

### ISSUE THREAD

**Issue by edmorley** [jeads/datasource#37]
Hi @jeads hope you are well :-)

Could you switch Travis on for this repo using the switch at https://travis-ci.org/profile please?
The `.travis.yml` config is in place so it should just work - I'm just not allowed to turn it on myself, not being the owner.

Thanks :-)

**Comment by jeads** [comment]
@edmorley I switched Travis on for datasource. Hope all is well with you too! Sorry for the slow response, I'm traveling for some clients at the moment.

**Comment by edmorley** [comment]
Is working well (https://travis-ci.org/jeads/datasource/builds/90932090) thank you :-)
Catch up soon!
